language: c
script:
  - asdf plugin test dart . --asdf-plugin-gitref $TRAVIS_COMMIT 'dart --version'

before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
