language: c
script:
  - asdf plugin-test dart $TRAVIS_BUILD_DIR 'dart --version' --asdf-tool-version 1.24.3

before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
